apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3tierwebapp-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vaishali1256/gitops-configs.git
    targetRevision: HEAD
    path: 3tier-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: 3tierwebapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m